CREATE TABLE role (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO role(name) VALUES ('CLIENT');
INSERT INTO role(name) VALUES ('EMPLOYEE');
INSERT INTO role(name) VALUES ('ADMIN');