spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    contexts: production
    drop-first: false

logging:
  level:
    root: INFO