spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  liquibase:
    contexts: test
    drop-first: true

logging:
  level:
    root: WARN