name: Build and Test

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: gradle/gradle-build-action@v1

      - name: Check code style
        run: ./gradlew checkstyleMain spotbugsMain --no-daemon

      - name: Build & run tests
        run: ./gradlew clean build jacocoTestReport --no-daemon

      - name: Upload quality reports
        uses: actions/upload-artifact@v3
        with:
          name: quality-reports
          path: |
            backend/build/reports/jacoco/jacocoTestReport/html
            backend/build/reports/checkstyle/main.html
            backend/build/reports/spotbugs/main.html

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/autosalon-backend:${{ github.ref_name }} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/autosalon-backend:${{ github.ref_name }}
