name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        working-directory: backend
        run: chmod +x ./gradlew

      - name: Build & generate reports
        working-directory: backend
        run: ./gradlew clean build jacocoTestReport checkstyleMain spotbugsMain

      - name: List all reports
        working-directory: backend
        run: |
          echo "=== Jacoco HTML files ==="
          find build/reports/jacoco/test/html -maxdepth 1 -type f
          echo "=== Checkstyle HTML ==="
          find build/reports/checkstyle -maxdepth 1 -type f
          echo "=== SpotBugs HTML ==="
          find build/reports/spotbugs -maxdepth 1 -type f

      - name: Upload quality reports
        uses: actions/upload-artifact@v3
        with:
          name: quality-reports
          path: |
            backend/build/reports/checkstyle
            backend/build/reports/spotbugs
            backend/build/reports/jacoco/test/html

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build & push Docker
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/autosalon-backend:latest
